"""ZugaLife therapist session note model.

SECURITY: This table is isolated from all other ZugaLife features.
Session notes must ONLY be queried by therapist/context.py and therapist/routes.py.
No other module (meditation, journal, habits, goals) should ever import from here.
"""

from datetime import datetime

from sqlalchemy import DateTime, Float, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from core.database.base import Base, TimestampMixin


class TherapistSessionNote(Base, TimestampMixin):
    """A summary note generated after a therapist conversation ends.

    The raw conversation is ephemeral (never stored). Only this structured
    summary persists, giving the therapist continuity across sessions.
    """

    __tablename__ = "therapist_session_notes"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[str] = mapped_column(String(64), index=True)

    # Session content (generated by AI at end of session)
    themes: Mapped[str] = mapped_column(Text, nullable=False)
    patterns: Mapped[str | None] = mapped_column(Text, nullable=True)
    follow_up: Mapped[str | None] = mapped_column(Text, nullable=True)
    mood_snapshot: Mapped[str | None] = mapped_column(String(50), nullable=True)

    # Session metadata
    message_count: Mapped[int] = mapped_column(Integer, default=0)
    cost: Mapped[float] = mapped_column(Float, default=0.0)

    # Mood tracking (before/after session)
    mood_before: Mapped[str | None] = mapped_column(String(32), nullable=True)
    mood_after: Mapped[str | None] = mapped_column(String(32), nullable=True)
    rating: Mapped[int | None] = mapped_column(Integer, nullable=True)  # 1-5 stars

    # Security: provider that processed this session (always "venice")
    provider: Mapped[str] = mapped_column(String(20), default="venice")
